"""Black-box Optimization Benchmarking in JAX."""

from .bbob import (
    BBOB_PROBLEMS,
    DIMENSIONS,
    AttractiveSector,
    BentCigar,
    BuecheRastrigin,
    DifferentPowers,
    Discus,
    Ellipsoidal,
    EllipsoidalRotated,
    Gallagher21Hi,
    Gallagher101Me,
    GriewankRosenbrock,
    Katsuura,
    LinearSlope,
    Lunacek,
    Rastrigin,
    RastriginRotated,
    Rosenbrock,
    RosenbrockRotated,
    SchaffersF7,
    SchaffersF7IllConditioned,
    Schwefel,
    SharpRidge,
    Sphere,
    StepEllipsoidal,
    Weierstrass,
    bbob_suite,
)
from .bbob_noisy import BBOB_NOISY_PROBLEMS, Noisy, bbob_noisy_suite
from .many_affine import ManyAffine
from .noise import (
    NOISE_MODELS,
    Cauchy,
    Gaussian,
    Mixture,
    Noiseless,
    NoiseModel,
    Uniform,
)
from .problem import BBOBEval, BBOBParams, BBOBProblem
from .qd import (
    AlignedProjection,
    Descriptor,
    FourierProjection,
    IrregularProjection,
    QDEval,
    QDParams,
    QDProblem,
    QuantizedProjection,
    RandomProjection,
    SubsetProjection,
    sphere_descriptor_optimum,
)
from .transforms import f_pen, lambda_alpha, transform_asy, transform_osz

__all__ = [
    # The contract, and the bbob suite built on it
    "BBOBProblem",
    "BBOB_PROBLEMS",
    "DIMENSIONS",
    "bbob_suite",
    # The 24, in canonical f1-f24 order
    "Sphere",
    "Ellipsoidal",
    "Rastrigin",
    "BuecheRastrigin",
    "LinearSlope",
    "AttractiveSector",
    "StepEllipsoidal",
    "Rosenbrock",
    "RosenbrockRotated",
    "EllipsoidalRotated",
    "Discus",
    "BentCigar",
    "SharpRidge",
    "DifferentPowers",
    "RastriginRotated",
    "Weierstrass",
    "SchaffersF7",
    "SchaffersF7IllConditioned",
    "GriewankRosenbrock",
    "Schwefel",
    "Gallagher101Me",
    "Gallagher21Hi",
    "Katsuura",
    "Lunacek",
    # Suites built from the 24, rather than one of them
    "Noisy",
    "BBOB_NOISY_PROBLEMS",
    "bbob_noisy_suite",
    "ManyAffine",
    # Quality-Diversity, composed onto a problem
    "QDProblem",
    "Descriptor",
    # The descriptor families, one per phenomenon
    "RandomProjection",
    "IrregularProjection",
    "QuantizedProjection",
    "FourierProjection",
    "SubsetProjection",
    "AlignedProjection",
    # Exact per-descriptor ground truth, where it exists in closed form
    "sphere_descriptor_optimum",
    # The transformations functions are built from, for building your own
    "lambda_alpha",
    "transform_osz",
    "transform_asy",
    "f_pen",
    # Noise models, held by a problem rather than switched on
    "NoiseModel",
    "NOISE_MODELS",
    "Noiseless",
    "Gaussian",
    "Uniform",
    "Cauchy",
    "Mixture",
    # The data types
    "BBOBParams",
    "BBOBEval",
    "QDParams",
    "QDEval",
]
