"""Black-box Optimization Benchmarking in JAX."""

from .functions import (
    BBOB_PROBLEMS,
    DIMENSIONS,
    AttractiveSector,
    BentCigar,
    BuecheRastrigin,
    DifferentPowers,
    Discus,
    Ellipsoidal,
    EllipsoidalRotated,
    Gallagher21Hi,
    Gallagher101Me,
    GriewankRosenbrock,
    Katsuura,
    LinearSlope,
    Lunacek,
    Rastrigin,
    RastriginRotated,
    Rosenbrock,
    RosenbrockRotated,
    SchaffersF7,
    SchaffersF7IllConditioned,
    Schwefel,
    SharpRidge,
    Sphere,
    StepEllipsoidal,
    Weierstrass,
    suite,
)
from .noise import (
    NOISE_MODELS,
    Additive,
    Cauchy,
    Gaussian,
    Mixture,
    Noiseless,
    NoiseModel,
    Uniform,
)
from .problem import BBOBEval, BBOBParams, BBOBProblem
from .qd import Descriptor, QDEval, QDParams, QDProblem, RandomProjection

__all__ = [
    # The contract, and the standard suite built on it
    "BBOBProblem",
    "BBOB_PROBLEMS",
    "DIMENSIONS",
    "suite",
    # The 24, in canonical f1-f24 order
    "Sphere",
    "Ellipsoidal",
    "Rastrigin",
    "BuecheRastrigin",
    "LinearSlope",
    "AttractiveSector",
    "StepEllipsoidal",
    "Rosenbrock",
    "RosenbrockRotated",
    "EllipsoidalRotated",
    "Discus",
    "BentCigar",
    "SharpRidge",
    "DifferentPowers",
    "RastriginRotated",
    "Weierstrass",
    "SchaffersF7",
    "SchaffersF7IllConditioned",
    "GriewankRosenbrock",
    "Schwefel",
    "Gallagher101Me",
    "Gallagher21Hi",
    "Katsuura",
    "Lunacek",
    # Quality-Diversity, composed onto a problem
    "QDProblem",
    "Descriptor",
    "RandomProjection",
    # Noise models, held by a problem rather than switched on
    "NoiseModel",
    "NOISE_MODELS",
    "Noiseless",
    "Gaussian",
    "Uniform",
    "Cauchy",
    "Additive",
    "Mixture",
    # The data types
    "BBOBParams",
    "BBOBEval",
    "QDParams",
    "QDEval",
]
